const teams=[{name:"EQUIPO ROJO",score:0,color:"red"},{name:"EQUIPO AZUL",score:0,color:"blue"},{name:"EQUIPO VERDE",score:0,color:"green"},{name:"EQUIPO AMARILLO",score:0,color:"yellow"}];

const rounds=[
{title:"REPORTE INICIAL",tag:"ALERTA ROJA",a:`<div class="doc-title">REPORTE INICIAL</div><div class="doc-box big-icon">🚨</div><div class="doc-line"><b>Ubicación:</b> Planta Base Solvente</div><div class="doc-line"><b>Equipo:</b> Tanque 34</div><div class="doc-line"><b>Evento:</b> Liberación de vapores inflamables</div>`,m:`<p>Analiza la escena inicial. El objetivo es descubrir qué fallas permitieron que el riesgo aumente.</p><div class="doc-ok">La clave está en los detalles. Observa, analiza y decide.</div>`,answer:"Reporte inicial",options:["Reporte inicial","MOC","PHA","PSI","Integridad Mecánica","Trabajos Críticos"],feedback:"Esta ronda es introductoria."},
{title:"LA AUTOPSIA DEL DOCUMENTO",tag:"RONDA 1",a:`<div class="doc-title">FICHA DEL PROCESO · TANQUE 34</div><div class="doc-box">🛢️ Temperatura máxima permitida: <b>55 °C</b><br>Solvente registrado: <b>Tipo A</b></div><div class="doc-line"><b>Material de línea:</b> Acero al carbono</div>`,m:`<p>Compara la ficha del proceso con la información del químico usado en el lote.</p><div class="doc-alert"><b>SDS nueva:</b> Solvente Tipo B genera mayor vapor inflamable sobre 50 °C y requiere revisión de compatibilidad.</div>`,answer:"PSI",options:["PSI","PHA","MOC","LOTO","ERP","Contratistas"],feedback:"Falló PSI: la información técnica del proceso no fue actualizada ni usada para validar límites, compatibilidad y condiciones seguras."},
{title:"INTERROGATORIO CRUZADO",tag:"RONDA 2",a:`<div class="doc-title">DECLARACIÓN DEL OPERADOR</div><div class="doc-box">👷 “La alarma de alta temperatura sonaba falso varias veces. Mantenimiento la puenteó para no detener producción.”</div>`,m:`<p>Determina por qué falló la salvaguarda principal.</p><div class="doc-alert"><b>Declaración supervisor:</b> En el HAZOP esa alarma era la salvaguarda crítica para evitar sobrecalentamiento.</div>`,answer:"PHA",options:["PHA","PSI","MOC","Auditorías","Emergencias","Capacitación"],feedback:"Falló PHA/gestión de salvaguardas: una barrera definida en HAZOP fue anulada sin analizar el riesgo."},
{title:"EL PAPELITO SOSPECHOSO",tag:"RONDA 3",a:`<div class="doc-title">ORDEN DE TRABAJO</div><div class="doc-box">🔧 “Se dañó la bomba original X-350. Se instaló temporalmente una X-200 para arrancar el turno de noche.”</div><div class="doc-alert">Queda pendiente revisar.</div>`,m:`<p>Identifica el error crítico del cambio temporal.</p><div class="doc-alert">La bomba X-200 tiene menor capacidad y diferente curva de operación.</div>`,answer:"MOC",options:["MOC","PSI","PHA","ERP","Investigación","Secretos Industriales"],feedback:"Falló MOC: un cambio temporal en equipo puede modificar caudal, presión, control del proceso y riesgo operativo."},
{title:"LA EVIDENCIA FÍSICA",tag:"RONDA 4",a:`<div class="doc-title">INSPECCIÓN EN CAMPO</div><div class="doc-box big-icon">🛢️</div><div class="doc-line">Manguera rígida con fisuras visibles.</div><div class="doc-alert">Última inspección documentada: hace 18 meses.</div>`,m:`<p>Evalúa qué control del sistema PSM debía evitar que se use un equipo deteriorado.</p><div class="doc-alert">Riesgo: pérdida de contención + vapores inflamables + fuente de ignición.</div>`,answer:"Integridad Mecánica",options:["Integridad Mecánica","MOC","PSI","Contratistas","LOTO","Auditorías"],feedback:"Falló Integridad Mecánica: el equipo crítico no fue inspeccionado ni mantenido oportunamente."},
{title:"EL CONTRATISTA Y LA CHISPA",tag:"RONDA 5",a:`<div class="doc-title">DECLARACIÓN CONTRATISTA</div><div class="doc-box">🔥 “Era una reparación urgente. Solo fueron 15 minutos de esmerilado cerca del área.”</div>`,m:`<p>Determina qué control faltó antes de realizar la tarea.</p><div class="doc-alert"><b>Permiso de trabajo en caliente:</b> NO ENCONTRADO.</div>`,answer:"Trabajos Críticos",options:["Trabajos Críticos","Contratistas","ERP","MOC","PSI","PHA"],feedback:"Fallaron Trabajos Críticos y control de contratistas: una fuente de ignición cerca de inflamables requiere permiso, controles y autorización."}
];

let currentRound=0,activeTeam=0,totalSeconds=0,roundSeconds=60,totalTimer=null,roundTimer=null;

const $=id=>document.getElementById(id);

function init(){
 renderScores(); populateTeams(); renderRound(); startTotalTimer();
 $("startRoundBtn").onclick=startRoundTimer; $("skipTeamBtn").onclick=nextTeam; $("prevRoundBtn").onclick=prevRound; $("nextRoundBtn").onclick=nextRound;
 $("correctBtn").onclick=()=>grade(50); $("partialBtn").onclick=()=>grade(25); $("wrongBtn").onclick=()=>grade(-10);
 $("resetBtn").onclick=()=>location.reload(); $("viewScoresBtn").onclick=showWinner; $("finishBtn").onclick=showWinner;
 $("closeModal").onclick=()=>$("winnerModal").classList.add("hidden"); $("playAgainBtn").onclick=()=>location.reload();
}
function startTotalTimer(){totalTimer=setInterval(()=>{totalSeconds++;let m=String(Math.floor(totalSeconds/60)).padStart(2,"0"),s=String(totalSeconds%60).padStart(2,"0");$("gameClock").textContent=`${m}:${s}`},1000)}
function renderScores(){let s=$("scoreStrip");s.innerHTML="";teams.forEach((t,i)=>{let d=document.createElement("div");d.className=`score-card ${t.color} ${i===activeTeam?"active":""}`;d.innerHTML=`<small>👥 ${t.name}</small><strong>${t.score}${i===0?" 🏆":""}</strong><div class="mini-bar"><i style="width:${Math.min(100,Math.max(5,t.score/5))}%"></i></div>`;s.appendChild(d)})}
function populateTeams(){let sel=$("teamSelect");sel.innerHTML="";teams.forEach((t,i)=>{let o=document.createElement("option");o.value=i;o.textContent=t.name;sel.appendChild(o)});sel.onchange=()=>{activeTeam=Number(sel.value);renderScores()}}
function renderRound(){let r=rounds[currentRound];$("roundIndicator").textContent=`${currentRound+1} de ${rounds.length}`;$("evidenceA").innerHTML=r.a;$("mission").innerHTML=`<p><b>${r.tag}: ${r.title}</b></p>${r.m}`;let a=$("answerSelect");a.innerHTML=`<option value="">Selecciona una opción...</option>`;r.options.forEach(opt=>{let o=document.createElement("option");o.value=opt;o.textContent=opt;a.appendChild(o)});$("feedback").className="feedback hidden";$("justification").value="";$("lastPoints").textContent="0";resetRoundTimer();renderDots();$("prevRoundBtn").disabled=currentRound===0;$("nextRoundBtn").disabled=currentRound===rounds.length-1}
function renderDots(){let dots=$("roundDots");dots.innerHTML="";rounds.forEach((_,i)=>{let d=document.createElement("div");d.className=`dot ${i===currentRound?"active":""} ${i<currentRound?"done":""}`;d.textContent=i+1;d.onclick=()=>{currentRound=i;renderRound()};dots.appendChild(d)})}
function startRoundTimer(){clearInterval(roundTimer);roundSeconds=60;updateClock();roundTimer=setInterval(()=>{roundSeconds--;updateClock();if(roundSeconds<=0){clearInterval(roundTimer);feedback("⏱ Tiempo agotado. Se continúa con el siguiente equipo.","bad");nextTeam()}},1000)}
function resetRoundTimer(){clearInterval(roundTimer);roundSeconds=60;updateClock()}
function updateClock(){let m=String(Math.floor(roundSeconds/60)).padStart(2,"0"),s=String(roundSeconds%60).padStart(2,"0");$("roundTimer").textContent=`${m}:${s}`}
function nextTeam(){activeTeam=(activeTeam+1)%teams.length;$("teamSelect").value=activeTeam;renderScores();resetRoundTimer()}
function grade(points){let selected=$("answerSelect").value;if(!selected){feedback("Selecciona una respuesta antes de calificar.","bad");return}let teamIndex=Number($("teamSelect").value);activeTeam=teamIndex;teams[teamIndex].score+=points;$("lastPoints").textContent=points>0?`+${points}`:points;let r=rounds[currentRound];if(points===50)feedback(`✅ Correcto. ${r.feedback}`,"good");else if(points===25)feedback(`🟡 Parcial. Elemento esperado: ${r.answer}. ${r.feedback}`,"good");else feedback(`❌ Incorrecto. Elemento esperado: ${r.answer}. ${r.feedback}`,"bad");renderScores();resetRoundTimer()}
function feedback(text,type){let fb=$("feedback");fb.textContent=text;fb.className=`feedback ${type==="good"?"good":"bad"}`}
function prevRound(){if(currentRound>0){currentRound--;renderRound()}}
function nextRound(){if(currentRound<rounds.length-1){currentRound++;renderRound()}}
function showWinner(){clearInterval(roundTimer);let sorted=[...teams].sort((a,b)=>b.score-a.score),winner=sorted[0];$("winnerTitle").textContent=`Ganador: ${winner.name}`;$("winnerText").textContent=`Felicitaciones. ${winner.name} obtuvo ${winner.score} puntos en la auditoría forense PSM.`;$("rankingList").innerHTML=sorted.map((t,i)=>`<div class="rank-row"><span>${i===0?"🏆":(i+1)+"."} ${t.name}</span><strong>${t.score} puntos</strong></div>`).join("");$("winnerModal").classList.remove("hidden")}
init();
