const scenes=[
{title:'Cambio de solvente',tag:'MOC',icon:'📦🧪',story:'Llegó un solvente de un nuevo proveedor. Parece similar, pero nadie revisó SDS, punto de inflamación ni compatibilidad.',opts:[['Usarlo porque parece equivalente.','Ahorra tiempo.',-10,25,'bad',null,'Mala decisión: un cambio químico/proveedor requiere evaluación formal.'],['Activar MOC antes de usarlo.','Revisar SDS, compatibilidad, almacenamiento y EPP.',25,-10,'ok','MOC','Correcto: MOC evita que un cambio pequeño termine en evento mayor.'],['Pedir aprobación verbal.','No queda evaluación técnica.',-5,15,'bad',null,'Insuficiente: PSM requiere aprobación documentada.'],['Guardarlo sin identificar.','Riesgo de confusión.',-15,30,'critical',null,'Crítico: químico sin información clara aumenta el riesgo.']]},
{title:'Manguera con fisuras',tag:'Integridad Mecánica',icon:'🛢️⚙️',story:'Antes del trasvase se observa una manguera rígida, desgastada y con fisuras. Producción pide iniciar rápido.',opts:[['Continuar y revisar después.','No se detiene la operación.',-20,35,'critical',null,'Crítico: puede generar pérdida de contención e incendio.'],['Detener, reportar y cambiar la manguera.','Control del equipo crítico.',30,-15,'ok','Integridad Mecánica','Correcto: Integridad Mecánica mantiene equipos críticos seguros.'],['Poner cinta temporal.','Solución rápida.',-10,20,'bad',null,'Incorrecto: reparación improvisada no controla el riesgo.'],['Que otro operador decida.','Traslada el problema.',-5,10,'bad',null,'Débil: PSM exige actuar ante señales tempranas.']]},
{title:'Temperatura fuera de límite',tag:'PHA',icon:'🌡️🔍',story:'La temperatura del tanque sube por encima del límite. Nadie sabe qué ocurriría si continúa aumentando.',opts:[['Analizar causas, consecuencias y controles.','Criterio PHA/HAZOP.',25,-10,'ok','PHA','Correcto: PHA analiza qué puede salir mal y qué barreras existen.'],['Esperar a que baje sola.','No se interviene.',-15,30,'critical',null,'Crítico: ignorar una desviación puede escalar el evento.'],['Abrir el tanque para enfriar.','Libera vapores.',-20,35,'critical',null,'Muy peligroso: puede liberar vapores inflamables.'],['Registrar al final del turno.','Documenta tarde.',-5,15,'bad',null,'Insuficiente: una desviación requiere acción inmediata.']]},
{title:'Trabajo en caliente',tag:'Trabajos Críticos',icon:'🔥🔧',story:'Un contratista debe soldar cerca del área de solventes. Hay presión porque el trabajo durará solo 20 minutos.',opts:[['Autorizar por experiencia.','Confianza personal.',-10,25,'bad',null,'Incorrecto: la experiencia no reemplaza el permiso.'],['Exigir permiso y controles.','Aislar, medir, retirar inflamables, vigía y extintor.',30,-15,'ok','Trabajos Críticos','Correcto: trabajos críticos requieren permisos y controles.'],['Hacerlo cuando no haya operadores.','Baja exposición de personas.',-15,30,'critical',null,'Crítico: la fuente de ignición sigue presente.'],['Hacerlo al final sin permiso.','Menos gente cerca.',-20,40,'critical',null,'Muy peligroso: trabajo caliente sin permiso cerca de inflamables.']]},
{title:'Intervención eléctrica',tag:'LOTO',icon:'🔒⚡',story:'Mantenimiento debe intervenir una bomba. Está apagada, pero no se bloqueó la energía ni se verificó energía cero.',opts:[['Trabajar porque está apagada.','Solo se usó botón de paro.',-20,35,'critical',null,'Crítico: apagar no es bloquear.'],['Aplicar LOTO.','Aislar, bloquear, etiquetar y verificar.',30,-15,'ok','LOTO','Correcto: LOTO controla energías peligrosas.'],['Que alguien vigile el botón.','Control débil.',-10,20,'bad',null,'Incorrecto: vigilar no sustituye bloqueo físico.'],['Desconectar rápido.','Terminar antes.',-15,30,'critical',null,'Peligroso: la prisa no controla energía peligrosa.']]},
{title:'Alarma fuera de servicio',tag:'PSSR / ERP',icon:'🚨📋',story:'Antes de arrancar, una alarma de nivel alto está fuera de servicio. Producción indica que el lote es urgente.',opts:[['Arrancar y mirar visualmente.','Control manual.',-10,25,'bad',null,'Insuficiente: la alarma crítica es una barrera.'],['Realizar revisión previa al arranque.','Evaluar barreras, riesgo residual y autorización.',25,-10,'ok','PSSR','Correcto: PSSR verifica seguridad antes del arranque.'],['Desactivar otras alarmas.','Evitar ruido.',-25,45,'critical',null,'Crítico: quitar barreras incrementa probabilidad de evento mayor.'],['Avisar solo por WhatsApp.','Comunicación informal.',-5,15,'bad',null,'Débil: condición crítica requiere gestión formal.']]},
{title:'Derrame de solvente',tag:'ERP',icon:'🛢️🚨',story:'Durante el trasvase ocurre un derrame. Hay olor fuerte, tránsito de personas y posibles fuentes de ignición.',opts:[['Limpiar rápido sin aislar.','Continuar operación.',-20,35,'critical',null,'Crítico: primero se aísla y se controla ignición.'],['Activar plan de emergencia.','Aislar, comunicar y usar kit adecuado.',35,-20,'ok','ERP','Correcto: ERP define respuesta ante derrames o incendios.'],['Esperar a que se evapore.','No intervenir.',-25,40,'critical',null,'Muy peligroso: vapores inflamables pueden encenderse.'],['Echar agua sin revisar SDS.','Improvisación.',-10,20,'bad',null,'Incorrecto: la respuesta debe seguir SDS y plan.']]}];
let current=0,risk=20,score=0,activated=new Set(),timer=null,timeLeft=0,answered=false;const $=id=>document.getElementById(id);
function startGame(){$('teamLabel').textContent=$('teamName').value||'Equipo PSM';$('start').classList.add('hidden');$('game').classList.remove('hidden');renderScene();}
function renderScene(){answered=false;const s=scenes[current];$('sceneNumber').textContent=`Escena ${current+1} de ${scenes.length}`;$('sceneTag').textContent=s.tag;$('sceneTitle').textContent=s.title;$('sceneStory').textContent=s.story;$('visual').textContent=s.icon;$('visual').className='visual';$('feedback').classList.add('hidden');$('nextBtn').classList.add('hidden');$('options').innerHTML='';s.opts.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.innerHTML=`<b>${String.fromCharCode(65+i)}. ${o[0]}</b><small>${o[1]}</small>`;b.onclick=()=>choose(o);$('options').appendChild(b);});setTimer();updateHud();}
function setTimer(){clearInterval(timer);const mode=$('mode').value;if(mode==='sin'){$('timer').textContent='--';return;}timeLeft=mode==='rapido'?20:45;$('timer').textContent=timeLeft+'s';timer=setInterval(()=>{timeLeft--;$('timer').textContent=timeLeft+'s';if(timeLeft<=0){clearInterval(timer);if(!answered)choose(['Tiempo agotado','',-10,15,'bad',null,'⏱ Tiempo agotado. En PSM la demora ante una condición crítica también aumenta el riesgo.']);}},1000);}
function choose(o){if(answered)return;answered=true;clearInterval(timer);score+=o[2];risk=Math.max(0,Math.min(100,risk+o[3]));if(o[5])activated.add(o[5]);const fb=$('feedback');fb.className='feedback '+o[4];fb.textContent=o[6];fb.classList.remove('hidden');$('visual').className='visual '+(o[4]==='ok'?'safe':o[4]==='critical'?'alert':'warning');$('nextBtn').classList.remove('hidden');document.querySelectorAll('.option').forEach(b=>b.disabled=true);updateHud();}
function nextScene(){current++;current>=scenes.length?endGame():renderScene();}
function updateHud(){$('score').textContent=score;$('riskValue').textContent=risk+'%';$('riskBar').style.width=risk+'%';if(risk<35){$('plantStatus').textContent='ESTABLE';$('plantStatus').style.color='#b8ffd4';}else if(risk<70){$('plantStatus').textContent='ALERTA';$('plantStatus').style.color='#ffe082';}else{$('plantStatus').textContent='CRÍTICO';$('plantStatus').style.color='#ffb4b4';}$('activated').innerHTML=[...activated].map(e=>`<span class="pill">${e}</span>`).join('')||'<p>Aún no se activan elementos.</p>';}
function endGame(){$('game').classList.add('hidden');$('end').classList.remove('hidden');const safe=risk<50;$('endTitle').textContent=safe?'✅ Planta segura: evento mayor evitado':'💥 Evento mayor: condición crítica';$('endMsg').textContent=safe?'El equipo tomó decisiones preventivas y aplicó controles PSM.':'Varias decisiones aumentaron el riesgo. Esto demuestra por qué PSM debe aplicarse antes de operar.';$('finalScore').textContent=score+' pts';$('finalRisk').textContent=risk+'%';$('finalStatus').textContent=safe?'Seguro':'Crítico';}
